### ISSUE TITLE
Automatically clean database dumps

### ISSUE THREAD

**Issue by steima** [variocube/devtools#11]
### Current Behaviour

We store database dump files in the `${WORK_DIR}/.databases` folder. These dumps never get deleted.

### Desired Behaviour

Security assessment at Pfizer says our approach is generally OK but we need to clear this data.

Whenever `devtools.sh` is called it should be able to run a set of cleanup tasks. One of these cleanup tasks is to delete old database dumps. We should delete all files older than 14 days from the `.databases` folder.

## Tasks

 - [ ] Implement infrastructure to support cleanup tasks
 - [ ] Implement database cleaning task
 - [ ] Report back to Pfizer once implemented
